name: CI
on: [pull_request]
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pip install ruff mypy jsonschema pyyaml
      - run: ruff .
      - run: mypy . || true
      - run: python policy_guard.py
